import { defineConfig } from "tsup";

export default defineConfig({
  entry: [
    "src/index.ts",
    "src/common/index.ts",
    "src/users/index.ts",
    "src/consultations/index.ts",
    "src/events/index.ts",
    "src/companies/index.ts",
    "src/bulletins/index.ts",
    "src/auth/index.ts",
    "src/endpoints/index.ts",
    "src/socket-events/index.ts",
    "src/validation/index.ts",
    "src/locales/index.ts",
    "src/feature-flags/index.ts",
    "src/magazines/index.ts",
    "src/headquarters/index.ts",
    "src/advisor-assignments/index.ts",
    "src/censuses/index.ts",
    "src/campuses/index.ts",
    "src/benefits/index.ts",
    "src/notifications/index.ts",
    "src/programs/index.ts",
  ],
  format: ["cjs", "esm"],
  dts: true,
  splitting: false,
  sourcemap: true,
  clean: true,
});
