/**
 * FAQ V2 validation limits — mirror backend Pydantic Field constraints.
 *
 * Frozen via `as const` so consumers cannot mutate at runtime.
 */
export const FAQ_LIMITS = {
  TITLE_MAX: 200,
  SUMMARY_MAX: 280,
  BODY_TOTAL_CHARS_MAX: 50_000,
  BODY_BLOCKS_MAX: 200,
  PARAGRAPH_TEXT_MD_MAX: 4000,
  HEADING_TEXT_MAX: 200,
  LIST_ITEMS_MAX: 50,
  LIST_ITEM_MAX: 500,
  QUOTE_TEXT_MAX: 600,
  QUOTE_SOURCE_MAX: 200,
  CALLOUT_TEXT_MD_MAX: 1500,
  CALLOUT_TITLE_MAX: 120,
  IMAGE_ALT_MAX: 300,
  IMAGE_CAPTION_MAX: 200,
  TABLE_HEADERS_MAX: 10,
  TABLE_ROWS_MAX: 50,
  GLOSSARY_TERM_MAX: 80,
  RELATED_CTA_LABEL_MAX: 120,
  CONSULTATION_CTA_LABEL_MAX: 120,
  LEGAL_DISCLAIMER_TEXT_MAX: 800,
  RESOURCE_FILE_MAX_BYTES: 20 * 1024 * 1024,
  RESOURCE_ENRICHMENT_TIMEOUT_MS: 5_000,
  SEARCH_Q_MIN: 2,
  SEARCH_Q_MAX: 200,
  SEARCH_LIMIT_MAX: 50,
  SUGGEST_LIMIT_MAX: 8,
  FEEDBACK_COMMENT_MAX: 1000,
} as const;
