#!/usr/bin/env bash
# Pull /tmp/v2_routes.json (generated by mini-back ``scripts/dump_v2_routes.py``)
# and convert it into a TypeScript constants module at
# ``src/endpoints/v2_endpoints_generated.ts``.
#
# Usage:
#   ./scripts/import-v2-endpoints.sh                          # uses /tmp/v2_routes.json
#   ./scripts/import-v2-endpoints.sh /path/to/v2_routes.json
#
# Mini-back side workflow:
#   cd ~/Desktop/WORK/mini-back && make dump-v2-routes
#
# Shared-types side (this repo):
#   ./scripts/import-v2-endpoints.sh
#   npm run build && npm run typecheck
#
# The generated file is committed to git for type-safe consumption by
# downstream frontend repos (sitimmApp, new_dashboard, Sitimm-web).
# Re-run this whenever mini-back V2 routes change.
#
# Closes TYPE-03 (shared-types side) from AUDIT_20260527.md.

set -euo pipefail

INPUT="${1:-/tmp/v2_routes.json}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
OUTPUT="${REPO_ROOT}/src/endpoints/v2_endpoints_generated.ts"

if [[ ! -f "${INPUT}" ]]; then
  echo "ERROR: input file not found: ${INPUT}" >&2
  echo "Hint: run 'make dump-v2-routes' in mini-back first." >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: node is required but was not found in PATH" >&2
  exit 1
fi

echo "Reading routes from ${INPUT}"
echo "Writing generated TS to ${OUTPUT}"

# Heavy lifting lives in a sibling Node script — the bash file just orchestrates.
node "${SCRIPT_DIR}/import-v2-endpoints.mjs" "${INPUT}" "${OUTPUT}"

echo "Done. Next steps:"
echo "  npm run build && npm run typecheck"
echo "  git add ${OUTPUT}"
